import { askScotty } from "@/lib/integrations/ai";

export type BotSpec = { name: string; prefix: string; description?: string; features: string[] };

export const BOT_FEATURES: Array<{ key: string; label: string }> = [
  { key: "menu", label: "Menu / help command" },
  { key: "ping", label: "Ping & uptime" },
  { key: "ai", label: "AI chat (uses your API key)" },
  { key: "sticker", label: "Sticker maker" },
  { key: "downloader", label: "Media downloader (permitted sources)" },
  { key: "group", label: "Group tools (tagall, welcome)" },
  { key: "antilink", label: "Anti-link protection" },
  { key: "quotes", label: "Quotes & jokes" },
];

const SNIPPETS: Record<string, string> = {
  menu: `  menu: async (sock, m) => reply(sock, m, "*" + BOT_NAME + "* commands:\\n" + Object.keys(commands).map((c) => PREFIX + c).join("\\n")),`,
  ping: `  ping: async (sock, m) => reply(sock, m, "Pong! Uptime: " + Math.floor(process.uptime()) + "s"),`,
  ai: `  ai: async (sock, m, args) => {
    if (!args.length) return reply(sock, m, "Usage: " + PREFIX + "ai <question>");
    const r = await fetch(process.env.AI_API_URL || "https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: "Bearer " + process.env.AI_API_KEY },
      body: JSON.stringify({ model: process.env.AI_MODEL || "openai/gpt-4o-mini", messages: [{ role: "user", content: args.join(" ") }] }),
    });
    const d = await r.json();
    return reply(sock, m, d?.choices?.[0]?.message?.content || "No answer.");
  },`,
  sticker: `  sticker: async (sock, m) => reply(sock, m, "Reply to an image with " + PREFIX + "sticker (add sharp/ffmpeg logic here)."),`,
  downloader: `  dl: async (sock, m, args) => reply(sock, m, args[0] ? "Downloader hook received: " + args[0] + " (connect your own permitted-source downloader)" : "Usage: " + PREFIX + "dl <link>"),`,
  group: `  tagall: async (sock, m) => {
    if (!m.key.remoteJid.endsWith("@g.us")) return reply(sock, m, "Groups only.");
    const meta = await sock.groupMetadata(m.key.remoteJid);
    const ids = meta.participants.map((p) => p.id);
    return sock.sendMessage(m.key.remoteJid, { text: "📣 Attention!\\n" + ids.map((i) => "@" + i.split("@")[0]).join(" "), mentions: ids });
  },`,
  antilink: `  // Anti-link runs on every message — see the messages.upsert handler below.`,
  quotes: `  quote: async (sock, m) => {
    const q = ["Talk is cheap. Show me the code.", "First, solve the problem. Then, write the code.", "Make it work, make it right, make it fast."];
    return reply(sock, m, q[Math.floor(Math.random() * q.length)]);
  },`,
};

/** Deterministic generator — always works, even if Scotty AI is not configured. */
export function buildBotFile(spec: BotSpec, extraCommands = ""): { filename: string; content: string } {
  const safe = spec.name.replace(/[^a-zA-Z0-9 _-]/g, "").slice(0, 40) || "ScottyBot";
  const prefix = (spec.prefix || ".").slice(0, 3).replace(/["\\\n]/g, "");
  const features = spec.features.filter((f) => SNIPPETS[f]);
  if (!features.includes("menu")) features.unshift("menu");
  const cmds = features.map((f) => SNIPPETS[f]).join("\n");
  const antilink = features.includes("antilink");

  const content = `/**
 * ${safe} — WhatsApp bot generated by Scotty AI (ScottyWorld)
 * ${spec.description ? spec.description.replace(/\*\//g, "") : "Custom bot"}
 *
 * SETUP
 *   1. Install Node.js 18+
 *   2. npm init -y && npm i @whiskeysockets/baileys pino qrcode-terminal
 *   3. node ${safe.toLowerCase().replace(/\s+/g, "-")}.js   (scan the QR code with WhatsApp > Linked devices)
 *
 * Keep your session folder (./auth) private — anyone with it controls the bot.
 */
const { default: makeWASocket, useMultiFileAuthState, DisconnectReason } = require("@whiskeysockets/baileys");
const pino = require("pino");
const qrcode = require("qrcode-terminal");

const BOT_NAME = ${JSON.stringify(safe)};
const PREFIX = ${JSON.stringify(prefix)};

const reply = (sock, m, text) => sock.sendMessage(m.key.remoteJid, { text }, { quoted: m });

const commands = {
${cmds}
${extraCommands}
};

async function start() {
  const { state, saveCreds } = await useMultiFileAuthState("./auth");
  const sock = makeWASocket({ auth: state, logger: pino({ level: "silent" }) });
  sock.ev.on("creds.update", saveCreds);

  sock.ev.on("connection.update", ({ connection, lastDisconnect, qr }) => {
    if (qr) qrcode.generate(qr, { small: true });
    if (connection === "open") console.log("✅ " + BOT_NAME + " connected");
    if (connection === "close") {
      const code = lastDisconnect?.error?.output?.statusCode;
      if (code !== DisconnectReason.loggedOut) start();
      else console.log("Logged out. Delete ./auth and restart.");
    }
  });

  sock.ev.on("messages.upsert", async ({ messages }) => {
    const m = messages[0];
    if (!m?.message || m.key.fromMe) return;
    const text = m.message.conversation || m.message.extendedTextMessage?.text || "";
${antilink ? `    if (/(https?:\\/\\/|chat\\.whatsapp\\.com)/i.test(text) && m.key.remoteJid.endsWith("@g.us")) {
      await sock.sendMessage(m.key.remoteJid, { delete: m.key }).catch(() => {});
      return;
    }` : ""}
    if (!text.startsWith(PREFIX)) return;
    const [name, ...args] = text.slice(PREFIX.length).trim().split(/\\s+/);
    const handler = commands[name.toLowerCase()];
    if (handler) { try { await handler(sock, m, args); } catch (e) { console.error(e); } }
  });
}

start();
`;
  return { filename: `${safe.toLowerCase().replace(/\s+/g, "-")}.js`, content };
}

/** Optionally ask Scotty AI for extra custom commands; falls back silently. */
export async function generateBot(spec: BotSpec & { idea?: string }) {
  let extra = "";
  if (spec.idea && (process.env.OPENROUTER_API_KEY || process.env.AI_API_KEY)) {
    try {
      const out = await askScotty([
        { role: "system", content: "You write JavaScript object-literal members for a Baileys WhatsApp bot `commands` object. Output ONLY members like `name: async (sock, m, args) => { ... },` with no markdown, no backticks, max 3 commands, no network calls to unknown hosts, no shell execution, no file deletion." },
        { role: "user", content: `Bot: ${spec.name}. Idea: ${spec.idea.slice(0, 500)}` },
      ], { temperature: 0.3 });
      const cleaned = out.replace(/```[a-z]*\n?|```/g, "").trim();
      const banned = /(child_process|exec\(|spawn\(|rm -rf|eval\(|Function\(|process\.env\.(?!AI_))/;
      if (cleaned && !banned.test(cleaned)) extra = cleaned;
    } catch { /* fall back to template only */ }
  }
  return buildBotFile(spec, extra);
}
