"use client";

import Link from "next/link";
import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Bot, Clock, Coins, Plus, RefreshCw, Sparkles, Zap } from "lucide-react";
import { Badge, Empty, ErrorNote, ListSkeleton, Page } from "@/components/ui";
import { BotGenerator } from "@/components/bot-generator";
import { api, useApi } from "@/lib/client";
import { ECONOMY } from "@/lib/economy";
import { toast } from "@/components/toast";

type B = { id: string; name: string; status: string; provider: string | null; hostedUntil: string | null; hasFile: boolean; source: string; hosting: { state: "ACTIVE" | "EXPIRING" | "EXPIRED"; daysLeft: number } };

function Bots() {
  const { data, loading, error, reload } = useApi<{ bots: B[]; limit: number; tier: string }>("/api/bots");
  const coins = useApi<{ balance: number }>("/api/coins");
  const [gen, setGen] = useState(false);
  const [renewing, setRenewing] = useState<string | null>(null);
  const sp = useSearchParams();
  useEffect(() => { if (sp.get("generate")) setGen(true); }, [sp]);

  async function renew(id: string) {
    setRenewing(id);
    try { await api(`/api/bots/${id}/renew`, { method: "POST" }); toast(`Hosting extended by ${ECONOMY.BOT_RENEW_DAYS} days`); await Promise.all([reload(), coins.reload()]); }
    catch (e: any) { toast(e.message, "err"); } finally { setRenewing(null); }
  }

  const bots = data?.bots ?? [];
  const tone = { ACTIVE: "green", EXPIRING: "amber", EXPIRED: "red" } as const;

  return (
    <Page>
      <div className="mb-3 flex items-center justify-between"><h1 className="text-2xl font-extrabold">Bots</h1>
        <Link href="/coins" className="flex items-center gap-1.5 rounded-full bg-amber-500/10 px-3 py-1.5 text-sm font-bold text-amber-700 dark:text-amber-300"><Coins size={15} />{coins.data?.balance ?? "…"} SC</Link></div>

      <div className="sw-card overflow-hidden">
        <div className="wallet-card p-4 text-white">
          <p className="flex items-center gap-2 text-sm font-bold"><Zap size={16} /> Bot hosting</p>
          <p className="mt-1 text-[13px] text-white/85">Every bot is hosted <b>free for {ECONOMY.BOT_FREE_DAYS} days</b>. Keep it online by renewing for <b>{ECONOMY.BOT_RENEW_COINS} SC</b> per {ECONOMY.BOT_RENEW_DAYS} days — earn coins from tasks.</p>
        </div>
        <div className="grid grid-cols-2 divide-x divide-border">
          <button onClick={() => setGen(true)} className="flex items-center justify-center gap-2 py-3.5 text-sm font-bold text-brand-600 hover:bg-soft"><Sparkles size={17} /> Generate with AI</button>
          <Link href="/bots/create" className="flex items-center justify-center gap-2 py-3.5 text-sm font-bold text-brand-600 hover:bg-soft"><Plus size={17} /> Add my bot</Link>
        </div>
      </div>

      <div className="mb-2 mt-6 flex items-center justify-between"><h2 className="text-[15px] font-bold">My bots</h2>{data && <span className="text-xs text-subtle">{bots.length}/{data.limit === -1 ? "∞" : data.limit} · {data.tier === "FREE" ? <Link href="/pro" className="font-semibold text-brand-600">Get more</Link> : data.tier}</span>}</div>
      {error && <ErrorNote message={error} onRetry={reload} />}
      {loading ? <ListSkeleton rows={2} /> : bots.length === 0 ? (
        <Empty icon={<Bot size={28} />} title="No bots yet" text="Generate a WhatsApp bot file with Scotty AI in under a minute." action={<button onClick={() => setGen(true)} className="sw-btn"><Sparkles size={17} /> Generate my first bot</button>} />
      ) : (
        <div className="space-y-3">
          {bots.map((b) => (
            <div key={b.id} className="sw-card p-4">
              <Link href={`/bots/${b.id}`} className="flex items-center gap-3">
                <span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-cyan-50 text-cyan-600 dark:bg-cyan-500/15"><Bot size={22} /></span>
                <div className="min-w-0 flex-1"><p className="truncate font-bold">{b.name}</p><p className="text-[13px] text-subtle">{b.source === "generated" ? "Generated by Scotty AI" : b.provider || "Custom bot"} · {b.status.toLowerCase()}</p></div>
                <Badge tone={tone[b.hosting.state]}>{b.hosting.state === "EXPIRED" ? "Expired" : b.hosting.state === "EXPIRING" ? "Expiring" : "Hosted"}</Badge>
              </Link>
              <div className="mt-3 flex items-center gap-3 border-t border-border pt-3">
                <p className="flex flex-1 items-center gap-1.5 text-[13px] text-subtle"><Clock size={14} />{b.hosting.state === "EXPIRED" ? "Hosting ended — renew to bring it back" : `${b.hosting.daysLeft} day${b.hosting.daysLeft === 1 ? "" : "s"} left`}</p>
                <button onClick={() => renew(b.id)} disabled={renewing === b.id} className="sw-btn !px-3.5 !py-2 text-xs"><RefreshCw size={14} className={renewing === b.id ? "animate-spin" : ""} /> Renew · {ECONOMY.BOT_RENEW_COINS} SC</button>
              </div>
            </div>
          ))}
        </div>
      )}
      <BotGenerator open={gen} onClose={() => setGen(false)} onDone={reload} />
    </Page>
  );
}

export default function BotsPage() { return <Suspense><Bots /></Suspense>; }
